In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (12,8)

In [2]:
df = pd.read_csv('Position_Salaries.csv')
X = df.iloc[:, 1:-1].values
y = df.iloc[:,-1].values

In [3]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
y = y.reshape(len(y),1)

In [6]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]])

In [7]:
from sklearn.preprocessing import StandardScaler
scale_x = StandardScaler()
scale_y =  StandardScaler()

X_scale = scale_x.fit_transform(X)
y_scale = scale_y.fit_transform(y)

In [10]:
from sklearn.svm import SVR

svr = SVR(kernel='rbf')
svr.fit(X_scale, y_scale)

/home/pranit/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [15]:
scale_y.inverse_transform(svr.predict(scale_x.transform([[6.5]])))

array([170370.0204065])